Mar-20 13:53:41.025 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf --run_order_mode -resume
Mar-20 13:53:41.157 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.10.1
Mar-20 13:53:41.182 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/chbope/.nextflow/plugins; core-plugins: nf-amazon@2.9.1,nf-azure@1.10.2,nf-cloudcache@0.4.2,nf-codecommit@0.2.2,nf-console@1.1.4,nf-google@1.15.2,nf-tower@1.9.3,nf-wave@1.7.3
Mar-20 13:53:41.200 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Mar-20 13:53:41.201 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Mar-20 13:53:41.204 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.12.0 in 'deployment' mode
Mar-20 13:53:41.217 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Mar-20 13:53:41.240 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/chbope/Documents/nanopore/clone/nextflow/nWGS_pipeline/nextflow.config
Mar-20 13:53:41.243 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/chbope/Documents/nanopore/clone/nextflow/nWGS_pipeline/nextflow.config
Mar-20 13:53:41.267 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/chbope/.nextflow/secrets/store.json
Mar-20 13:53:41.271 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@545607f2] - activable => nextflow.secret.LocalSecretsProvider@545607f2
Mar-20 13:53:41.287 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Mar-20 13:53:42.284 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declaration
Mar-20 13:53:42.304 [main] DEBUG nextflow.cli.CmdRun - Launching `main.nf` [dreamy_bassi] DSL2 - revision: 94b27fc596
Mar-20 13:53:42.306 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Mar-20 13:53:42.306 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Mar-20 13:53:42.359 [main] DEBUG nextflow.Session - Session UUID: 29143127-0df9-41a3-8ac4-91d857693215
Mar-20 13:53:42.360 [main] DEBUG nextflow.Session - Run name: dreamy_bassi
Mar-20 13:53:42.360 [main] DEBUG nextflow.Session - Executor pool size: 12
Mar-20 13:53:42.369 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Mar-20 13:53:42.374 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=36; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Mar-20 13:53:42.396 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 24.10.1 build 5930
  Created: 18-11-2024 12:21 UTC (13:21 CEST)
  System: Linux 5.4.0-208-generic
  Runtime: Groovy 4.0.23 on OpenJDK 64-Bit Server VM 11.0.15-internal+0-adhoc..src
  Encoding: UTF-8 (UTF-8)
  Process: 2157806@chbope [127.0.1.1]
  CPUs: 12 - Mem: 78.2 GB (24 GB) - Swap: 6 GB (6 GB)
Mar-20 13:53:42.469 [main] DEBUG nextflow.Session - Work-dir: /home/chbope/Documents/nanopore/clone/nextflow/nWGS_pipeline/work [ext2/ext3]
Mar-20 13:53:42.524 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Mar-20 13:53:42.537 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Mar-20 13:53:42.595 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Mar-20 13:53:42.609 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 13; maxThreads: 1000
Mar-20 13:53:42.620 [main] ERROR nextflow.cli.Launcher - Unable to acquire lock on session with ID 29143127-0df9-41a3-8ac4-91d857693215

Common reasons for this error are:
 - You are trying to resume the execution of an already running pipeline
 - A previous execution was abruptly interrupted, leaving the session open

You can see which process is holding the lock file by using the following command:
 - lsof /home/chbope/Documents/nanopore/clone/nextflow/nWGS_pipeline/.nextflow/cache/29143127-0df9-41a3-8ac4-91d857693215/db/LOCK
java.io.IOException: Unable to acquire lock on session with ID 29143127-0df9-41a3-8ac4-91d857693215

Common reasons for this error are:
 - You are trying to resume the execution of an already running pipeline
 - A previous execution was abruptly interrupted, leaving the session open

You can see which process is holding the lock file by using the following command:
 - lsof /home/chbope/Documents/nanopore/clone/nextflow/nWGS_pipeline/.nextflow/cache/29143127-0df9-41a3-8ac4-91d857693215/db/LOCK
	at nextflow.cache.DefaultCacheStore.openDb(DefaultCacheStore.groovy:91)
	at nextflow.cache.DefaultCacheStore.open(DefaultCacheStore.groovy:106)
	at nextflow.cache.DefaultCacheStore.open(DefaultCacheStore.groovy)
	at nextflow.cache.CacheDB.open(CacheDB.groovy:59)
	at nextflow.Session.init(Session.groovy:441)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:129)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:376)
	at nextflow.cli.Launcher.run(Launcher.groovy:503)
	at nextflow.cli.Launcher.main(Launcher.groovy:658)
